version: '3.4'

services:
  player.api:
    container_name: player-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=playerdb;Database=PlayerDb;User Id=sa;Password=SwN12345678;MultipleActiveResultSets=true
    ports:
      - "8001:80"
  playerdb:
    container_name: playerdb
    environment:
        SA_PASSWORD: "SwN12345678"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
        - "1433:1433"
  nosqldb:
    container_name: nosqldb
    restart: always
    ports:
        - "27017:27017"
    volumes:
        - mongo_data:/data/db
  teams.api:
    container_name: teams-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://nosqldb:27017"
    ports:
      - "8002:80"

