version: '3.4'

services:
  player.api:
    image: ${DOCKER_REGISTRY-}playerapi
    build:
      context: .
      dockerfile: Services/Player.API/Dockerfile
  teams.api:
    image: ${DOCKER_REGISTRY-}teamsapi
    build:
      context: .
      dockerfile: Services/Teams.API/Dockerfile



  playerdb:
    image: mcr.microsoft.com/mssql/server:2017-latest
    volumes:
      - sqldata:/var/opt/mssql
  nosqldb:
    image: mongo

  rabbitmq:
    image: rabbitmq:3-management-alpine
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2
volumes:
   sqldata:
    external: false
   mongo_data:
   elasticsearch-data:



