version: '3.4'

services:
  player.api:
    image: ${DOCKER_REGISTRY-}playerapi
    build:
      context: .
      dockerfile: Services/Player.API/Dockerfile
  playerdb:
    image: mcr.microsoft.com/mssql/server:2017-latest
    volumes:
      - sqldata:/var/opt/mssql

volumes:
   sqldata:
    external: false

